### ISSUE TITLE
Make generated code selectable 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [GroovinChip/dart_class_generator#3]
I couldn't hold to copy from mobile on the web app

**Comment by GroovinChip** [comment]
Yeah it's intentionally left to the copy button. Less work. I could make it a user setting though.

**Comment by ThinkDigitalSoftware** [comment]
Shouldn't that be the user's choice? Or that's the way you like it? Users are used to text being copyable on the web unless for some reason it's sensitive

**Comment by GroovinChip** [comment]
Fair enough, I could make it a user setting

**Comment by ThinkDigitalSoftware** [comment]
Ok, thank you, sir!

**Comment by GroovinChip** [comment]
Working on this now @ThinkDigitalSoftware

**Comment by GroovinChip** [comment]
Turning on code editing for the code viewer doesn't seem to work. I will speak to Rody.

**Comment by GroovinChip** [comment]
OK Version 0.0.5 allows an editable code viewer. However, the source code does not currently support selecting code nor does it support accurate cursor location. I know Rody has gotten it to work in https://flutterweb.app but that code is not public.

**Comment by ThinkDigitalSoftware** [comment]
OK, thank you
