### ISSUE TITLE
[Bug] Making a class member private breaks the code view

### ISSUE THREAD

**Issue by darthdie** [GroovinChip/dart_class_generator#5]
Steps to Reproduce:
1. Go to site.
2. Create a new class member (name and type don't appear to matter)
3. Click the overflow menu for the member and hit "Make Private"

The code view turns grey (`rgb(66, 66, 66)` to be exact) and the console displays:
```
blank message here | js_primitives.dart:49
Another exception was thrown: Instance of 'minified:fa<void>' | js_primitives.dart:49
```

Changing the window size causes the latter issue to be continually printed, however I can't imagine that it's a different issue.

**Comment by darthdie** [comment]
It works fine when named parameters are enabled.

**Comment by GroovinChip** [comment]
Thank you, will look into this
